### ISSUE TITLE
Drag'n'drop is not handy

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson-PageBuilder-Extension#25] opened 2015-03-13 14:28 UTC
As seen on this video I made, sometimes it's nearly impossible to place a block : https://www.youtube.com/watch?v=iphLrknR9go&feature=youtu.be

The block is not going to the section I want, sometimes goes back to the top of the builder, nests where I don't want it too... etc.
I think they should be some "reserved spaces" for dropping blocks, the same way Wordpress does it on its dashboard, because right now it's not very handy

**Comment by GheorgheP** [comment] 2015-03-23 10:04
Hi,

Yes, we know that at the moment builder has some inconveniences, in this commit we reduced the ma little bit: https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/68186232101ff10145462ff62917b73358a858ad

We are still working on that and solve as soon as possible.

**Comment by ierpe** [comment] 2015-04-20 08:59
Hey, check out this really cool drag'n'drop library : http://bevacqua.github.io/dragula/
Maybe it could save you some time to use it for the page builder, it seems very stable!

**Comment by moldcraft** [comment] 2015-04-20 09:31
http://jqueryui.com/sortable/#connect-lists also seems stable, but in more advanced scenarios the flaws start to appear.

We will take a look if it's possible to replace [sortable](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/c4d38a1724e84370fcb30421d411a99ad46314dd/includes/option-types/builder/static/js/builder.js#L374-L629) with [dragula](https://github.com/bevacqua/dragula#usage).

If you want, you can edit the [builder.js](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/c4d38a1724e84370fcb30421d411a99ad46314dd/includes/option-types/builder/static/js/builder.js#L374-L379) and play with [sortable parameters](http://api.jqueryui.com/sortable/), maybe we will find a combination that works without glitches.

**Comment by ierpe** [comment] 2015-04-22 10:03
Actually this one might even be a better candidate since it seems it is based on sortable : http://johnny.github.io/jquery-sortable/

**Comment by moldcraft** [comment] 2015-05-13 19:21
Can you please [download](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/archive/master.zip) the dev version of PageBuilder and install it in `unyson/framework/extensions/shortcodes/extensions/page-builder`?

I made the placeholder visible

[ ![s](http://static.md/6daa0ee3899ea785cef652b8ea792935.png) ](https://static.md/6daa0ee3899ea785cef652b8ea792935.png)

I think it should help understand/visualize better where the shortcode will be placed.

**Comment by moldcraft** [comment] 2015-05-13 19:22
updated comment above

**Comment by moldcraft** [comment] 2015-05-15 15:24
I changed the [sortable tolerance parameter](http://api.jqueryui.com/draggable/#option-snapTolerance) to  `pointer` and I think it's a game changer. Please [test it](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/67).

**Comment by moldcraft** [comment] 2015-05-15 15:27
I changed the [sortable tolerance parameter](https://api.jqueryui.com/sortable/#option-tolerance) to  `pointer` and I think it's a game changer. Please [test it](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/67).

**Comment by ierpe** [comment] 2015-05-18 12:08
I tried but cannott test as I get the following error : 

```
PHP Fatal error:  Extension "editor-shortcodes" is already defined in "/home/piero/www/pesticides/web/app/plugins/unyson/framework/extensions/builder/extensions/editor-shortcodes" found again in "/home/piero/www/pesticides/web/app/plugins/unyson/framework/extensions/shortcodes/extensions/page-builder/extensions/editor-shortcodes" in /home/piero/www/pesticides/web/app/plugins/unyson/framework/core/components/extensions.php on line 173, referer: http://loc-pesticides.org/wp/wp-admin/edit-comments.php
```

**Comment by moldcraft** [comment] 2015-05-18 16:23
Delete `unyson/framework/extensions/builder/extensions`

**Comment by ierpe** [comment] 2015-05-19 09:26
This is what I did in the first place... but I still have the problem and connot test it :(

**Comment by moldcraft** [comment] 2015-05-20 15:06
You can delete the entire plugin and reinstall it via admin panel. The changes are already in production.

**Comment by moldcraft** [comment] 2015-05-25 09:29
Have you tried it? Can I close this issue?

**Comment by ierpe** [comment] 2015-05-25 20:29
Hey, yes I tried and I still have some problems of sections / blocks nesting with each other when they shouldn't :-/
Sorry it was a long weekend here, I didn't have time yet, but I'll post some screenshots tomorrow

**Comment by moldcraft** [comment] 2015-05-25 20:31
Ok, no problem. Thank you for feedback.

**Comment by ierpe** [comment] 2015-05-26 10:25
Ok here is a bug I cannot reproduce everytime, so I could not capture it in a video, but I have a screenshot : 

![screenshot-nested-section](https://cloud.githubusercontent.com/assets/790992/7810215/65a89c3e-03a0-11e5-8547-08f28dfba30d.png)

As you can see after moving a section around, it ends up nested into another section... otherwise the drag'n'drop definitely seems better, compared to when I opened the issue!

Although I think it is still complicated to use with "big" layouts, because you just cannot have an overview of the whole blocks... will there be a front-end visual editor at some point?

As a side note, I think the builder "header" is way too big, and should at least minimize itself when scrolling down or when moving some blocks around : 

![screenshot-builder-header-is-too-big](https://cloud.githubusercontent.com/assets/790992/7810395/e396c930-03a1-11e5-94ca-7f425ccd2095.png)

I am working on a 1600x900 laptop screen, and the area to work with the blocks is just too small (and does not get bigger in fullscreen mode...)
What do you think?

**Comment by moldcraft** [comment] 2015-07-22 10:00
TODO: On drag, show shortcode square thumbnail http://joxi.ru/l2ZYnzKClBonmJ

**Comment by moldcraft** [comment] 2015-07-24 14:39
TODO: On drag, placeholder should be sizeless (to not bother other elements on the page) to be with position absolute (or something similar) and to be displayed as a line http://joxi.ru/V2VvR06UBeG62v

**Comment by danyj** [comment] 2015-07-27 12:16
@moldcraft  If you don't mind ,  what is that   "ideal"  builder you made video off ?

**Comment by moldcraft** [comment] 2015-07-27 12:17
https://ukit.com

**Comment by moldcraft** [comment] 2015-09-01 10:38
https://github.com/bevacqua/dragula/issues/190

If you have any ideas or know a solution, please share.

**Comment by moldcraft** [comment] 2015-09-14 22:12
The above issue was closed :|

I will try to integrate dragula as it is, I hope it will work fine/handy.

**Comment by dominicht** [comment] 2015-09-28 19:30
I took a quick look at ukit.com and their solution looks great. I'm not a pro at this, but it seems like the reason why it's hard to put elements at the right place is because your placeholder is a big relative div that moves other elements around when you drag it. 

If think you could reproduce something like ukit.com by modifying the ".fw-builder-placeholder" div css and give it 0px width / 100% height or  0px height / 100% width depending on if the object you're dragging is between columns or elements.

Hope this makes sense.

**Comment by moldcraft** [comment] 2015-09-28 19:45
I tried that https://github.com/ThemeFuse/Unyson-Builder-Extension/tree/handy

Still has glitches (the placeholder moves very fast back and forth)

**Comment by ierpe** [comment] 2015-10-29 10:22
Hi, any updates on this?
The flickering is still very present...

**Comment by moldcraft** [comment] 2015-10-29 10:57
I am currently working on Backup v2. Then a very important task is https://github.com/ThemeFuse/Unyson/issues/838 . Then I will try to implement this https://github.com/bevacqua/dragula/pull/197

**Comment by ierpe** [comment] 2015-10-29 10:59
Nice, waiting for it!

**Comment by moldcraft** [comment] 2015-11-05 19:21
*(temporarily closed) just testing something*

**Comment by moldcraft** [comment] 2015-12-22 22:14
Finished [dragula](https://github.com/bevacqua/dragula) integration. Everything is on [this branch](https://github.com/ThemeFuse/Unyson-Builder-Extension/tree/handy-dragula) ([diff](https://github.com/ThemeFuse/Unyson-Builder-Extension/compare/handy-dragula))

Unfortunately:

* A [very important feature](https://github.com/bevacqua/dragula/issues/121) is missing
* They refused to add a delay parameter and [this pull request has a bug](https://github.com/bevacqua/dragula/pull/197#issuecomment-166742105) and I don't know if that user will reply and fix it. So no delay feature.

**Please test if it's handier than jquery sortable**

**Comment by danyj** [comment] 2015-12-23 11:30
@moldcraft  testing

**Comment by danyj** [comment] 2015-12-23 11:35
@moldcraft  anything special I should look for , this looks ok to me

**Comment by danyj** [comment] 2015-12-23 12:09
I see what delay did , the columns are dancing around until you drop the one you are moving.

**Comment by danyj** [comment] 2015-12-23 12:12
bug , cant move clicked section,  did not drag but clicked on 1/4 column , it drooped under the section and I cant move it anymore http://prntscr.com/9hm0nu

**Comment by moldcraft** [comment] 2015-12-23 12:13
Can you make a video please?

**Comment by danyj** [comment] 2015-12-23 12:13
sure sec

**Comment by danyj** [comment] 2015-12-23 12:15
http://screencast.com/t/JOv3ESBfUET

**Comment by moldcraft** [comment] 2015-12-23 12:17
thanks

**Comment by danyj** [comment] 2015-12-23 12:23
Can you adjust this if possible 
http://screencast.com/t/gzGKgem2

left to right movements require you to go more right in order to trigger the move , 
up/down are ok and right to left seem ok also.

**Comment by danyj** [comment] 2015-12-23 12:27
in prev video I  resized the browser to make video smaller , but on full screen that left to right takes longer ,see here 
http://screencast.com/t/jFRLg0A30WY

**Comment by moldcraft** [comment] 2015-12-24 14:49
I [tried](https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/1790fee9c668ceb0b7f47239b0b2ba15a1ab3070) this [parameter](https://github.com/bevacqua/dragula#optionsdirection) but it creates the "jumping" [glitch](https://vid.me/1irG)

**Comment by DominicTobias** [comment] 2016-01-05 12:26
Unfortunately this prevents me from using this great lib and throwing out jquery ui, which works for vertical and horizontal dragging without changes. In a list view dragula works will, but in a grid view it doesn't! Unfortunately I don't have the maths powa to help, but it's great you guys are working on it I hope you manage to figure it out!

**Comment by moldcraft** [comment] 2016-05-21 18:09
How about this https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/68287d79959fd3759235011dcd1b5584c203194a ? Please test

You can play with [timeout value](https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/68287d79959fd3759235011dcd1b5584c203194a#diff-3dd8370dbf7af1232d4d1c62cac4b59eR653)

**Comment by danyj** [comment] 2016-06-03 21:10
@moldcraft  this is bad man  http://www.screencast.com/t/DadsxPB0XI

**Comment by moldcraft** [comment] 2016-06-03 21:37
In that video you don't use [this change](https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/68287d79959fd3759235011dcd1b5584c203194a), the placeholder must not be visible while moving.

**Comment by danyj** [comment] 2016-06-03 21:47
looks better ,  another issue now is placing the item between sections  is harder  and moving columns right to left is still an issue,  http://screencast.com/t/bvK6Yw9kmB

**Comment by danyj** [comment] 2016-06-03 21:48
I dont know your setup but I am on 27" monitor so my boxes are big thus I need move moving room

**Comment by danyj** [comment] 2016-06-03 21:52
but here I resized the browser and this is plain trouble and very hard to move around. If you lucky that you dont have to move elements once placed you ok , otherwise it is trouble , look at this till the end please http://screencast.com/t/frYDJhvBf3

**Comment by moldcraft** [comment] 2016-06-03 22:04
Yes, not a good solution.

It will be good if jquery sortable will allow placeholder repossition delay, I will try to emulate it somehow.

**Comment by duongancol** [comment] 2016-06-08 01:54
@moldcraft not sure it's better, but I found that library, that not using Jquery sortable, it's just javascript but the demo is good. Please take a look here: http://rubaxa.github.io/Sortable/

**Comment by moldcraft** [comment] 2016-06-08 09:19
@duongancol I tried that library, it "shakes" too

**Comment by danyj** [comment] 2016-06-08 09:26
horizontal and vertical movements seem ok, @moldcraft  what do u mean by "shakes"

**Comment by duongancol** [comment] 2016-06-08 09:28
@danyj  see [here](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/54)

**Comment by danyj** [comment] 2016-06-08 09:29
@duongancol ,  ah yeah,  that is pain

**Comment by moldcraft** [comment] 2016-06-08 13:23
I think this is the silver bullet https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/98355fe8ea784362e8557c8bf7a730d56f0be32f

Please [Download](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/archive/master.zip) and test

**Comment by danyj** [comment] 2016-06-08 13:24
@moldcraft  on it

**Comment by danyj** [comment] 2016-06-08 13:31
@moldcraft  less "shaky" but still  hard to work with  http://screencast.com/t/dLYdJzrR8

**Comment by moldcraft** [comment] 2016-06-08 13:38
I think in your video is not this fix. The elements are still moving fast, on 0:35. View page source, builder.js and check if [this code](https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/98355fe8ea784362e8557c8bf7a730d56f0be32f) is there

**Comment by moldcraft** [comment] 2016-06-08 13:40
Ops, put the wrong link in above comment.

Download this https://github.com/ThemeFuse/Unyson-Builder-Extension/archive/master.zip
in `unyson/framework/extensions/builder`

**Comment by danyj** [comment] 2016-06-08 13:41
>Ops, put the wrong link in above comment.

yes you did ,  I just cheeked , redownloading

**Comment by danyj** [comment] 2016-06-08 13:45
left and  right are much better , up and down still an issue , http://screencast.com/t/iIen7lbMDQVe
but this is improvement for sure.

**Comment by moldcraft** [comment] 2016-06-08 13:49
Thank you. Inspecting...

**Comment by moldcraft** [comment] 2016-06-08 13:51
P.S. At the moment dragging from top (new shortcodes) doesn't work

**Comment by danyj** [comment] 2016-06-08 13:53
> P.S. At the moment...

I see  , this is what it just did ,  http://prntscr.com/bdvds3

**Comment by moldcraft** [comment] 2016-06-09 13:37
Playing with parameters and events without success. Drag'n'drop is pain

![](https://static.md/ae83fb002f1bc3474ee36a261d613bc9.png)

**Comment by danyj** [comment] 2016-06-09 13:41
it is

**Comment by moldcraft** [comment] 2016-06-09 14:06
I can't solve the problem by setting the right parameters and manipulating the placeholder via events.

The last solution is to copy jquery sortable, dig in code and delay placeholder update from there.

**Comment by danyj** [comment] 2016-06-09 14:09
@moldcraft   , you think you be able to maintain the changes https://github.com/jquery/jquery-ui/blob/master/ui/widgets/sortable.js, I mean if you do and you find time please do it , as you see know the builder is awesome with all options  but compared to other D&D&'s we have a mess , and is pain on large pages

**Comment by duongancol** [comment] 2016-06-09 14:37
@moldcraft : Could you try to include sortable.js and modify it? we need to test if it works better. Then if yes, I think it's not bad solution.

**Comment by moldcraft** [comment] 2016-06-10 14:24
https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/97213cd0ac625ad62be51f938f3441740b43cdbf

Please test: Download https://github.com/ThemeFuse/Unyson-Builder-Extension/archive/master.zip in `unyson/framework/extensions/builder` (or `git pull`)

**Comment by danyj** [comment] 2016-06-10 14:26
on it

**Comment by danyj** [comment] 2016-06-10 14:31
I say is bit to slow now , but again up/down  does not work right , I think we need more top/bottom padding in sections in order to find it right place

http://screencast.com/t/poIuUtZvoRJ

**Comment by danyj** [comment] 2016-06-10 14:36
@moldcraft   and I think you know that drag from top leaves traces , http://prntscr.com/beq67i
just reminder if you dont.

**Comment by moldcraft** [comment] 2016-06-10 14:37
thanks, I will play with timeout value

P.S. Maybe switch to https://monosnap.com ? your screencast links don't work in my browser https://static.md/e953f13a663c730ddad2a68cbed31753.png I always open them in Firefox

**Comment by danyj** [comment] 2016-06-10 14:38
>Maybe switch 

did not know that screencast does not have html5 version ,  
install flash :)

**Comment by danyj** [comment] 2016-06-10 14:47
here is the video https://monosnap.com/file/LuuvnkqKeYExTK4B3U35mLcU6VlY5h

**Comment by moldcraft** [comment] 2016-06-10 15:34
I decreased a bit the timeout https://github.com/ThemeFuse/Unyson-Builder-Extension/commit/8fc0048c37559f01f88865bfe957f503bac39c32#diff-3dd8370dbf7af1232d4d1c62cac4b59eR704 and fixed the bug with traces.

I think this is all I can do for now. We'll see/test how it works and maybe do some improvements in future.

**Comment by danyj** [comment] 2016-06-10 15:42
you might want to check that trace again , second you try to move element in section it creates it right under
http://take.ms/Nzp7n

**Comment by moldcraft** [comment] 2016-06-10 16:15
The main problem with "jumping" of elements is fixed. The glitches with positioning will be inspected later.

**Comment by duongancol** [comment] 2016-06-17 05:20
I know it's not the best solution but just want to share our way to make the drap&rop more handy between colum: http://take.ms/YEn24
just changed some CSS and I think we can re-structure the layout to make it's better.

**Comment by danyj** [comment] 2016-06-17 09:51
@duongancol nice one.  try ,  this 

```
col - col -col 
       col //  move me above and under the top ones
```

**Comment by duongancol** [comment] 2016-06-18 04:53
@danyj : see here: https://monosnap.com/file/y7KS0Mr87p3bNToDlJjLMim4YPeNRq

**Comment by danyj** [comment] 2016-06-18 07:04
no bud , this , 
http://prntscr.com/bhtycq

move the column with video above the top 3 columns

**Comment by duongancol** [comment] 2016-06-18 07:23
not stable : http://take.ms/GcJWg

**Comment by danyj** [comment] 2016-06-18 07:24
@duongancol ,  yeah thought so , that is one we cant fix, thnx for testing

**Comment by danyj** [comment] 2016-06-18 07:25
try to add more top padding to the section , see if that helps , this gap here , http://prntscr.com/bhu39u

**Comment by duongancol** [comment] 2016-06-18 07:33
It's not better

**Closed** 2018-03-13 13:07 UTC
Labels: enhancement
